name: Compile Latex courses

run-name: Compile courses

on: [push]

jobs:

  build_beginner_course:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: courses/01_beginners/
          pre_compile: |
            pwd
            tlmgr update --self && tlmgr update --all
            latexminted --version
          root_file: main.tex
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf