# __________________________________________________
#
# Workflow to test the slide compilation
# __________________________________________________

name: Generate courses PDF

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'courses/**'

jobs:
  build_beginner_course:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: courses/01_beginners/
          pre_compile: |
            tlmgr update --self && tlmgr update minted
            latexminted --version
          root_file: main.tex
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
