# __________________________________________________
#
# Workflow to compile and run all exercises
# __________________________________________________

name: Test exercises

on:
  pull_request:
    branches:
      - main
    paths:
      - 'exercises/**'

jobs:

  build_test_exercises:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Prepare all exercices and solutions with the OpenMP backend
        run: |
          cmake \
            -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DKokkos_ENABLE_OPENMP=ON \
            exercises
      - name: Build all exercises and solutions
        run: |
          cmake \
            --build build \
            --parallel $(($(nproc) * 2 + 1))
      - name: Test all solutions
        env:
          OMP_PROC_BIND: spread
          OMP_PLACES: threads
          OMP_NUM_THREADS: 2
        run: |
          ctest \
            --test-dir build \
            --output-on-failure
