# __________________________________________________
#
# Workflow to compile and run all exercises
# __________________________________________________

name: Test exercises

on:
  pull_request:
    branches:
      - main
    paths:
      - 'exercises/**'

jobs:

  build_test_exercises:
    runs-on: ubuntu-latest
    env:
      OMP_PROC_BIND: spread
      OMP_PLACES: threads
      OMP_NUM_THREADS: 2
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Prepare all exercices and solutions with the OpenMP backend
        run: |
          cmake \
            -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DKokkos_ENABLE_OPENMP=ON \
            exercises
      - name: Build all exercises and solutions
        run: |
          cmake \
            --build build \
            --parallel $(($(nproc) * 2 + 1))
      - name: Test solution 01
        run: build/01_first_program/solution/exe01solution
      - name: Test solution 02
        run: build/02_basic_view/solution/exe02solution
      - name: Test solution 03
        run: build/03_deep_copy/solution/exe03solution
      - name: Test solution 04
        run: build/04_parallel_loop/solution/exe04solution
      - name: Test solution 05
        run: build/05_parallel_reduce/solution/exe05solution
