# __________________________________________________
#
# Workflow to compile and run all projects
# __________________________________________________

name: Test projects

on:
  pull_request:
    branches:
      - main
    paths:
      - 'projects/**'

jobs:

  build_test_projects:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Prepare all projects with the OpenMP backend
        run: |
          cmake \
            -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DKokkos_ENABLE_OPENMP=ON \
            projects
      - name: Build all projects
        run: |
          cmake \
            --build build \
            --parallel $(($(nproc) * 2 + 1))
      - name: Test all solutions and reference implementations
        env:
          OMP_PROC_BIND: spread
          OMP_PLACES: threads
          OMP_NUM_THREADS: 2
        run: |
          ctest \
            --test-dir build \
            --output-on-failure
