# __________________________________________________
#
# Workflow to check spelling on the whole project
# __________________________________________________

name: Check spelling

on:
  pull_request:

jobs:
  check_spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.29.7
